input_boolean:
  follow_music:
    name: Follow Music
    initial: off

input_select:
  music_controller:
    name: Music Controller
    options:
      - living_room
      - office
      - kitchen
      - music
    initial: music

script:
  sonos_group_motion:
    alias: sonos group motion
    sequence:
      - condition: template
        value_template:
          "{% if target_player is not none and target_player != false and
          target_player != '' %}\n  true\n{% else %}\n  false\n{% endif %}\n"
      - condition: template
        value_template:
          "{% if states(target_player) != 'playing' %}\n  true\n{% else
          %}\n  false\n{% endif %}\n"
      - service: media_player.volume_set
        data_template:
          entity_id:
            "{% if target_player is not none %}\n  {{ target_player }}\n{% endif
            %}\n"
          volume_level:
            "{% for state in states.media_player if state.entity_id == 'media_player.'
            + states('input_select.music_controller') %}\n  {{state.attributes.volume_level
            }}\n{% endfor %}\n"
      - service: media_player.join
        data_template:
          entity_id: media_player.{{ states('input_select.music_controller') }}
          group_members:
            "{% if target_player is not none %}\n  {{ target_player }}\n{%
            endif %}\n"
    description: ""
  sonos_ungroup_motion:
    alias: Sonos Ungroup Motion
    sequence:
      - condition: template
        value_template:
          "{% if target_player is not none and target_player != false and
          target_player != '' %}\n  true\n{% else %}\n  false\n{% endif %}\n"
      - condition: template
        value_template:
          "{% if states(target_player) == 'playing' %}\n  true\n{% else
          %}\n  false\n{% endif %}\n"
      - condition: template
        value_template:
          "{% if target_player != 'media_player.' + states('input_select.music_controller')
          %}\n  true\n{% else %}\n  false\n{% endif %}\n"
      - service: media_player.unjoin
        data_template:
          entity_id:
            "{% if target_player is not none %}\n  {{ target_player }}\n{% endif
            %}\n"
    description: ""


automation:
- id: '1760706991041'
  alias: Join music
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.slaapkamer_multisensor_slaapkamer_pir_sensor
    id: Werkkamer beweging
    to: 'on'
    alias: Werkkamer beweging
  - type: motion
    device_id: 218bf4e29ea2fb6bfe9c99b9e91db680
    entity_id: 8411400df35c752762047f0d8f942acf
    domain: binary_sensor
    trigger: device
    id: keuken beweging
    alias: keuken beweging
  conditions:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.follow_music
      state: 'on'